<?php
/*
 You may not change or alter any portion of this comment or credits
 of supporting developers from this source code or any supporting source code
 which is considered copyrighted (c) material of the original comment or credit authors.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

$modversion['dirname'] = basename(dirname(__FILE__));
$modversion['name'] = ucfirst(basename(dirname(__FILE__)));
$modversion['version'] = '1.0';
$modversion['description'] = 'This is a dummy module.';
$modversion['author'] = "noone";
$modversion['credits'] = "nobody@localhost";
$modversion['help'] = 'page=help';
$modversion['license'] = "GNU GPL 2 or later";
$modversion['license_url'] = 'http://www.gnu.org/licenses/old-licenses/gpl-2.0.html';
$modversion['official'] = 0;
$modversion['image'] = "images/dummy.png";

$modversion['hasMain'] = 1;

$modversion['onInstall'] = "include/install.inc.php";

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['system_menu'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu']  = "admin/menu.php";

/*
$i = 0;
$i++;
$modversion['config'][$i]['name'] = 'config1';
$modversion['config'][$i]['title'] = '_MI_DUMMY_CONFIG1';
$modversion['config'][$i]['description'] = '_MI_DUMMY_CONFIG2_DSC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'this is my test config1 value';

$i++;
$modversion['config'][$i]['name'] = 'config2';
$modversion['config'][$i]['title'] = '_MI_DUMMY_CONFIG2';
$modversion['config'][$i]['description'] = '_MI_DUMMY_CONFIG2_DSC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'this is my test config2 value';
*/
// About stuff
$modversion['module_status'] = 'Alpha';
$modversion['status'] = 'Alpha';
$modversion['release_date'] = '08/28/2013';

$modversion['min_xoops'] = '2.6.0';
$modversion['min_php'] = '5.3.7';

// Admin menu
// Set to 1 if you want to display menu generated by system module
$modversion['system_menu'] = 1;

// Admin things
$modversion['hasAdmin']   = true;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu']  = 'admin/menu.php';

// Manage extension
$modversion['extension'] = 1;
$modversion['extension_module'][] = 'system';
